I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/src/locations/concertLocation.rpy", line 3, in script
    call screen town
ScriptError: could not find label 'library_location'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Program Files (Development)\Renpy\renpy\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "D:\Program Files (Development)\Renpy\renpy\renpy\main.py", line 487, in main
    run(restart)
  File "D:\Program Files (Development)\Renpy\renpy\renpy\main.py", line 147, in run
    renpy.execution.run_context(True)
  File "D:\Program Files (Development)\Renpy\renpy\renpy\execution.py", line 761, in run_context
    context.run()
  File "game/src/locations/concertLocation.rpy", line 3, in script
    call screen town
  File "D:\Program Files (Development)\Renpy\renpy\renpy\script.py", line 858, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'library_location'.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Dating Languages 1.0
